-- MySQL Script generated by MySQL Workbench
-- Sat Sep 23 19:44:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blogs` (
  `idblogs` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idblogs`),
  INDEX `fk_blogs_usuarios_iduser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_blogs_usuarios_iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`usuarios` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_administrador_blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_administrador_blog` (
  `idusuario_administrador_blog` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idblog` INT NOT NULL,
  PRIMARY KEY (`idusuario_administrador_blog`),
  INDEX `fk_usuario_administrador_blog_usuarios_iduser_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_usuario_administrador_blog_blogs_idblog_idx` (`idblog` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_administrador_blog_usuarios_iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`usuarios` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_administrador_blog_blogs_idblog`
    FOREIGN KEY (`idblog`)
    REFERENCES `mydb`.`blogs` (`idblogs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registros_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registros_usuario` (
  `idpagina_visitada` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `pagina_visitada` VARCHAR(45) NOT NULL,
  `fecha_visita` DATETIME NOT NULL,
  `tiempo_en_pagina` TIME NOT NULL,
  `direccion_ip` VARCHAR(45) NOT NULL,
  `Navegador_web` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpagina_visitada`),
  INDEX `fk_registros_usuario_usuarios_iduser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_registros_usuario_usuarios_iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`usuarios` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `idpublicaciones` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `contenido` VARCHAR(45) NULL,
  `idblog` INT NOT NULL,
  `idusuario_administrador_blog` INT NOT NULL,
  PRIMARY KEY (`idpublicaciones`),
  INDEX `fk_publicaciones_blogs_idblog_idx` (`idblog` ASC) VISIBLE,
  INDEX `fk_publicaciones_blogs_idblog_idx1` (`idusuario_administrador_blog` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_blogs_idblog`
    FOREIGN KEY (`idblog`)
    REFERENCES `mydb`.`blogs` (`idblogs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicaciones_usuario_administrador_blog_idusuario_administrador_blog`
    FOREIGN KEY (`idusuario_administrador_blog`)
    REFERENCES `mydb`.`usuario_administrador_blog` (`idusuario_administrador_blog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `idcomentarios` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `iduser` INT NOT NULL,
  `idpublicacion` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuarios_iduser_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones_idpublicacion_idx` (`idpublicacion` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios_iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`usuarios` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones_idpublicacion`
    FOREIGN KEY (`idpublicacion`)
    REFERENCES `mydb`.`publicaciones` (`idpublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
